<a href="https://colab.research.google.com/github/ChristeenaGiji/NLP/blob/main/Word2Vec%2CAvgWord2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install gensim

In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec, KeyedVectors

In [4]:
import gensim.downloader as api
wv =api.load('word2vec-google-news-300')
vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [6]:
wv['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [ ]:
wv.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [ ]:
wv.most_similar('king')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [7]:
wv.similarity('man','king')

0.22942673

In [ ]:
vec=wv['king']-wv['man']+wv['woman']
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [8]:
import pandas as pd
messages =pd.read_csv('/content/SMSSpamCollection.txt',sep='\t',names=['label','message'])

In [9]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
messages.shape

(5572, 2)

In [ ]:
messages['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

#Spam Classifion Dataset

1. Text preprocessing : Tokenization, stopwords, stemming,lemmization, NLTK
2. Text to vectors : BOW, TFIDF,Word2Vec,AvgWord2Vec

In [10]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [11]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [14]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [13]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

#1. BOW

In [15]:
#Creating BOW model
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,binary=True,ngram_range=(1,2))
X=cv.fit_transform(corpus).toarray()

In [16]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X.shape

(5572, 2500)

In [ ]:
X[1]

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,1].values

In [18]:
#Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [19]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
X_train.shape

(4457, 2500)

In [21]:
y_train.shape

(4457,)

In [22]:
X_test.shape

(1115, 2500)

In [ ]:
y_test.shape

(1115,)

In [23]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [24]:
#prediction
y_pred=spam_detect_model.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [26]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9865470852017937


In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.99      1.00      0.99       955
        True       0.98      0.93      0.95       160

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



#2. TFIDF

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X=cv.fit_transform(corpus).toarray()

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [30]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [31]:
#prediction
y_pred=spam_detect_model.predict(X_test)

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
score=accuracy_score(y_test,y_pred)
print(score)

0.97847533632287


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.98      1.00      0.99       955
        True       1.00      0.85      0.92       160

    accuracy                           0.98      1115
   macro avg       0.99      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115



#3.  We can also use Random forest

In [34]:
from sklearn.ensemble import RandomForestClassifier
spam_detect_model=RandomForestClassifier().fit(X_train,y_train)
spam_detect_model.fit(X_train,y_train)

RandomForestClassifier()

In [35]:
y_pred=spam_detect_model.predict(X_test)
accuracy_score(y_test,y_pred)

0.9847533632286996

In [36]:
print (classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.98      1.00      0.99       955
        True       1.00      0.89      0.94       160

    accuracy                           0.98      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.98      0.98      1115



#4. Word2Vec Implementation

2 types:
skigram and CBOW



In [37]:
!pip install gensim

In [ ]:
import gensim.downloader as api
wv =api.load('word2vec-google-news-300')

In [38]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [39]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [40]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [41]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [42]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess


In [ ]:
corpus[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [43]:
import gensim
from gensim.utils import simple_preprocess

# Process each document in the corpus individually(lowering case)
processed_corpus = [simple_preprocess(doc) for doc in corpus]

In [44]:
import nltk
nltk.download('punkt')

from nltk import sent_tokenize
from gensim.utils import simple_preprocess

words=[]
for sent in corpus:
  sent_token=sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

  words.append(simple_preprocess(sent))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [56]:
import nltk
nltk.download('punkt')

from nltk import sent_tokenize
from gensim.utils import simple_preprocess

words=[]
for sent in corpus:
  sent_token=sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

  words.append(simple_preprocess(sent))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [57]:
words[:5]

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply']]

In [46]:
# avg vector for every sentence we require 120 Dimension
import gensim
model=gensim.models.Word2Vec(words,vector_size=120,window=10,min_count=2,workers=4)

In [47]:
# to see all vocabulary
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'go',
 'lt',
 'day',
 'ok',
 'free',
 'know',
 'come',
 'like',
 'good',
 'time',
 'got',
 'love',
 'text',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'min',
 'night',
 'make',
 'dear',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'great',
 'claim',
 'hope',
 'oh',
 'hey',
 'give',
 'number',
 'happy',
 'friend',
 'work',
 'wat',
 'yes',
 'way',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'win',
 'said',
 'amp',
 'cash',
 'life',
 'yeah',
 'im',
 'really',
 'babe',
 'meet',
 'find',
 'miss',
 'morning',
 'service',
 'uk',
 'last',
 'year',
 'thanks',
 'care',
 'com',
 'would',
 'anything',
 'lol',
 'nokia',
 'also',
 'every',
 'feel',
 'keep',
 'sure',
 'pick',
 'urgent',
 'sent',
 'contact',


In [ ]:
model.corpus_count

11136

In [ ]:
model.epochs

5

In [48]:
model.wv.similar_by_word('happy')

[('morning', 0.9976629614830017),
 ('good', 0.9972221851348877),
 ('return', 0.9970036745071411),
 ('hope', 0.9968396425247192),
 ('night', 0.9956323504447937),
 ('love', 0.9953165054321289),
 ('well', 0.9950836896896362),
 ('day', 0.994533360004425),
 ('life', 0.9945326447486877),
 ('wake', 0.9943573474884033)]

In [ ]:
model.wv['kid'].shape

(120,)

In [60]:
#remove ot-of-vocabulary word
#avgword2vec to each vocabulary
#next get average output in model for every word(word here is sentence)usingtqdm

def avg_word2vec(doc):
    #remove ot-of-vocabulary word
    #sent =[word for word i doc if word in model.wv.index_to_key]
    #print(sent)
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0) # Indented this line by 4 spaces

In [ ]:
# words are sentence
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though

In [63]:
!pip install tqdm
from tqdm import tqdm
import numpy as np # Import numpy and assign it the alias 'np'

X=[]
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

#remove ot-of-vocabulary word
#get output in model for every vocabulary
def avg_word2vec(doc):
    #remove ot-of-vocabulary word
    #sent =[word for word i doc if word in model.wv.index_to_key]
    #print(sent)
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0) # Indented this line by 4 spaces

  0%|          | 0/11136 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 11136/11136 [00:02<00:00, 4522.99it/s]


In [ ]:
words[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amore',
 'wat']

In [ ]:
#Vectors for 1st sentence
X[0]

array([-0.05410051,  0.12740543,  0.21010183,  0.23597834, -0.21930982,
        0.07793711,  0.16044652,  0.17803185,  0.07060369,  0.08686687,
        0.14575924,  0.13768457,  0.60722005, -0.41830185, -0.36321214,
       -0.14087604, -0.27309042, -0.05821012, -0.38310105, -0.09137835,
       -0.10496508, -0.40315035,  0.325185  , -0.3047357 , -0.0790041 ,
       -0.33163315, -0.17002073,  0.03373519, -0.18880436, -0.36062652,
        0.07037632, -0.6305808 ,  0.28955868, -0.13860641, -0.10478711,
        0.2086487 ,  0.20630504, -0.6855138 , -0.616063  ,  0.04585953,
        0.08137833,  0.07148451, -0.21091768,  0.08507217,  0.413315  ,
        0.00187206,  0.08988418,  0.01297148, -0.29851627,  0.26003   ,
       -0.45804664,  0.2016755 ,  0.06007838,  0.5124261 ,  0.12349676,
        0.51437724, -0.08754831, -0.01748175,  0.4097293 , -0.45666912,
        0.09407715,  0.37728003, -0.23818722,  0.11319163, -0.01190165,
       -0.29817384,  0.32356095,  0.5946254 , -0.0111364 , -0.07

In [ ]:
# to see the dimension
X[0].shape

(120,)

In [58]:
# to see all my input features
X

[array([-2.74526095e-03,  8.88248906e-02,  2.31929556e-01,  2.02632546e-01,
        -1.75030068e-01,  8.35450366e-02,  2.09338143e-01,  2.16665581e-01,
         4.33614887e-02,  7.38848969e-02,  1.29832223e-01,  1.51707873e-01,
         5.51129401e-01, -4.49477434e-01, -3.60919952e-01, -1.25868812e-01,
        -2.55906254e-01, -7.81042054e-02, -4.02669489e-01, -9.49873403e-02,
        -9.52458456e-02, -3.68305624e-01,  2.63519049e-01, -3.13449383e-01,
        -9.54689905e-02, -3.30205619e-01, -1.79376081e-01,  3.71093154e-02,
        -1.91109851e-01, -3.26504558e-01,  1.08166151e-01, -6.47391915e-01,
         2.67256796e-01, -1.54169694e-01, -7.35785812e-02,  2.30433255e-01,
         2.59439677e-01, -7.17902601e-01, -5.67431033e-01,  6.04630411e-02,
         9.96615142e-02,  3.57499160e-02, -2.02399507e-01,  7.87656456e-02,
         4.14494306e-01, -4.84644290e-04,  4.73002903e-02,  3.39545645e-02,
        -2.71200925e-01,  2.76631325e-01, -4.44925636e-01,  2.25132570e-01,
        -1.9

In [54]:
#DO TRAIN AND TEST SPLIT